"""
AI Report Generator
Uses Groq (Llama 3.3 70B) to generate plain-English leakage
reports from anomaly detection results.
"""

import os
import sqlite3
import pandas as pd
from dotenv import load_dotenv
from groq import Groq
from datetime import datetime

# ── Setup ─────────────────────────────────────────────────────────
load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH  = os.path.join(BASE_DIR, "data", "db", "leakage.db")

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def load_anomalies() -> pd.DataFrame:
    """Load anomaly results from database."""
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql_query(
        """
        SELECT *
        FROM anomaly_results
        WHERE confidence_score >= 40
        ORDER BY confidence_score DESC
        """,
        conn
    )
    conn.close()
    print(f"✅ Loaded {len(df)} anomalies for reporting")
    return df


def generate_zone_report(zone_data: pd.Series) -> str:
    """Generate a plain-English report for a single anomaly."""

    prompt = f"""
You are a senior water network analyst at a UK water utility company.
Analyse the following leakage detection data and write a professional
operational report for the field team.

ZONE INFORMATION:
- Zone ID: {zone_data['zone_id']}
- Zone Name: {zone_data['zone_name']}
- Zone Size: {zone_data['zone_size']}
- Date: {str(zone_data['reading_date'])[:10]}

SENSOR READINGS:
- Minimum Night Flow (MNF): {zone_data['mnf_ls']} L/s
- Network Pressure: {zone_data['pressure_m']} metres
- Acoustic Logger Alert: {'YES' if zone_data['acoustic_alert'] == 1 else 'NO'}

STATISTICAL ANALYSIS:
- MNF Z-Score: {round(zone_data['mnf_zscore'], 2)} (above 2.5 = anomalous)
- Pressure Z-Score: {round(zone_data['pressure_zscore'], 2)}
- Rolling Average MNF: {zone_data['mnf_rolling_avg']} L/s
- Confidence Score: {zone_data['confidence_score']}/100
- Severity: {zone_data['severity']}
- Risk Level: {zone_data['risk_level']}

Write a concise professional report (150-200 words) that includes:
1. A clear alert headline
2. What the data shows in plain English
3. What type of leakage event this likely is
4. Recommended immediate action for the field team
5. Priority level

Use professional water industry language but keep it clear and actionable.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=400
    )
    return response.choices[0].message.content


def generate_full_report(df: pd.DataFrame) -> str:
    """Generate a complete report for all anomalies."""
    print("\n🤖 Generating AI reports for each anomaly...\n")

    report_date = datetime.now().strftime("%d %B %Y")
    full_report = f"""
{'='*65}
WATER NETWORK LEAKAGE DETECTION REPORT
Generated: {report_date}
System: AI-Powered Leakage Detector v1.0
{'='*65}

EXECUTIVE SUMMARY
─────────────────
Total anomalies detected: {len(df)}
Critical events: {len(df[df['severity'] == 'Critical'])}
High severity: {len(df[df['severity'] == 'High'])}
Medium severity: {len(df[df['severity'] == 'Medium'])}

{'='*65}
DETAILED ZONE REPORTS
{'='*65}
"""

    for i, (_, row) in enumerate(df.iterrows()):
        print(f"   Generating report {i+1}/{len(df)}: "
              f"{row['zone_id']} {row['zone_name']}...")
        zone_report = generate_zone_report(row)
        full_report += f"""
{'─'*65}
ZONE: {row['zone_id']} — {row['zone_name']} | Score: {row['confidence_score']}/100
{'─'*65}
{zone_report}
"""

    full_report += f"""
{'='*65}
END OF REPORT
Generated by Leakage AI Detector
Author: Siddharth Shekhar Singh
{'='*65}
"""
    return full_report


def save_report(report: str) -> str:
    """Save the report to the docs folder."""
    report_date = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(
        BASE_DIR, "docs", f"leakage_report_{report_date}.txt"
    )
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n✅ Report saved to: {report_path}")
    return report_path


def main():
    print("🌊 AI Leakage Report Generator\n")
    print("="*65)

    df       = load_anomalies()
    report   = generate_full_report(df)
    filepath = save_report(report)

    print("\n" + "="*65)
    print("📄 REPORT PREVIEW (first 2000 chars):")
    print("="*65)
    print(report[:2000])
    print("\n🎉 Report generation complete!")
    print(f"   Full report saved to: {filepath}")


if __name__ == "__main__":
    main()